name: CI Web Admin

on:
    - pull_request

jobs:
    build:
        name: Build Web
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3

            - name: Install Packages
              run: npm i

            - name: Build
              run: npm run build
